import * as Print from "expo-print";

const formatDate = (date) => {
  return new Date(date).toLocaleDateString();
};

export const printTransactionsReport = async (transactions) => {
  if (!transactions || transactions.length === 0) {
    throw new Error("No transactions available to print");
  }

  const totalAmount = transactions.reduce(
    (total, transaction) => total + Number(transaction.amount || 0),
    0,
  );

  const transactionRows = transactions
    .map(
      (transaction) => `
        <tr>
          <td>${formatDate(transaction.date)}</td>
          <td>${transaction.name}</td>
          <td>${transaction.category || "Other"}</td>
          <td class="amount">₹${Number(transaction.amount).toFixed(2)}</td>
        </tr>
      `,
    )
    .join("");

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <style>
          body {
            font-family: Arial, sans-serif;
            padding: 24px;
            color: #172033;
          }

          h1 {
            margin-bottom: 4px;
          }

          .subtitle {
            color: #667085;
            margin-bottom: 24px;
          }

          .summary {
            display: flex;
            justify-content: space-between;
            margin-bottom: 24px;
          }

          .summary-card {
            border: 1px solid #EAECF0;
            padding: 12px;
            width: 45%;
          }

          .label {
            color: #667085;
            font-size: 12px;
          }

          .value {
            font-size: 20px;
            font-weight: bold;
            margin-top: 4px;
          }

          table {
            width: 100%;
            border-collapse: collapse;
          }

          th {
            background: #F6F7FB;
            text-align: left;
          }

          th,
          td {
            border: 1px solid #EAECF0;
            padding: 8px;
            font-size: 12px;
          }

          .amount {
            text-align: right;
          }

          .total-row {
            font-weight: bold;
            background: #F6F7FB;
          }

          .footer {
            margin-top: 24px;
            color: #667085;
            font-size: 11px;
          }
        </style>
      </head>

      <body>
        <h1>SpendWise</h1>

        <div class="subtitle">
          Expense Report — ${new Date().toLocaleDateString()}
        </div>

        <div class="summary">
          <div class="summary-card">
            <div class="label">Transactions</div>
            <div class="value">${transactions.length}</div>
          </div>

          <div class="summary-card">
            <div class="label">Total Expenses</div>
            <div class="value">₹${totalAmount.toFixed(2)}</div>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Expense</th>
              <th>Category</th>
              <th>Amount</th>
            </tr>
          </thead>

          <tbody>
            ${transactionRows}

            <tr class="total-row">
              <td colspan="3">TOTAL</td>
              <td class="amount">₹${totalAmount.toFixed(2)}</td>
            </tr>
          </tbody>
        </table>

        <div class="footer">
          Generated by SpendWise
        </div>
      </body>
    </html>
  `;

  await Print.printAsync({
    html,
  });
};
